[project]
name = "17-deploying-open-source-endpoints"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.3.2",
    "dotenv>=0.9.9",
    "jupyter>=1.1.1",
    "langchain>=0.3.27",
    "langchain-community>=0.3.31",
    "langchain-core>=0.3.79",
    "langchain-together>=0.3.1",
    "langgraph>=1.0.1",
    "langgraph-cli[inmem]>=0.4.7",
    "langgraph-sdk>=0.2.9",
    "qdrant-client>=1.15.1",
    "tiktoken>=0.12.0",
]
